pagopa/rtp-platform-qa

- config.yaml
- contract-tests/test_api_create_rtp.py
- utils/dataset.py
- ux-tests/tests/test_navigation.py
This PR proposes to add a test for frontend validation.
- add UX test for comma amount
Run:
> feat: [SRTP-60] Add test for comma amount

- README.md
- config.yaml
- contract-tests/test_activation.py
- contract-tests/test_api_create_rtp.py
This PR proposes to add contract testing for activation service.
Run:
> feat: [SRTP-84] Add activation contract tests

- utils/dataset.py
- ux-tests/tests/test_navigation.py
This PR proposes to add a test case to ensure form filling doesn't clean whitespaces.
Run:
> feat: [SRTP-167] Add test on whitespaces 

- api/activation.py
- bdd-tests/steps/activation_steps.py
- bdd-tests/steps/debtor_steps.py
- functional-tests/tests/test_activation.py
This PR proposes to add the API to obtain activation given debtor fiscal code.
- add API
- adapt tests
With this change we can check whether a debtor has been activate successfully and by whom.
Run:
> feat: [SRTP-189] add get activation API

- functional-tests/tests/test_activation.py
- functional-tests/tests/test_send_rtp.py
- ux-tests/tests/test_navigation.py
This PR proposes to add a test on lower case fiscal code.
Run:
> feat: [SRTP-201] Fiscal code must be lower case

- .github/workflows/doc_page.yaml
- .github/workflows/run_tests.yml
- bdd-tests/Creditor Service Provider/send_RTP_through_API.feature
- bdd-tests/Creditor Service Provider/send_RTP_through_web_page.feature
- bdd-tests/Debtor Service Provider/features/activation.feature
- scenarios_parser.py
This PR proposes to add a doc page that gathers all features and relative scenarios implemented.
Run:
> feat: [SRTP-170] add scenarios parser

- api/send_rtp.py
- config.yaml
- functional-tests/tests/test_activation.py
- functional-tests/tests/test_send_rtp.py
- utils/dataset.py
- ux-tests/tests/test_navigation.py
This PR proposes to adapt tests to new developments.
- move version to header instead of path
- change send payload structure
Run:
> fix: [SRTP-208] Update tests with new RTP mapping

- functional-tests/tests/test_send_rtp.py
This PR proposes to add a test case of mocked server received after a send.
Run:
> feat: [SRTP-195] Receive mocked response

- performance-tests/send.js
- performance-tests/utility.js
This PR proposes to add a first script for performance testing. The script must be executed manually and locally.
- add k6 utility
- add k6 script to load test send 
With this change we can start loading our system.
Run:
> feat: [SRTP-235] Add send performance tests scripts

- functional-tests/tests/test_activation.py
This PR enforces an assertion error on message returned in body of malformed requests.
Run:
> feat: [SRTP-190] add check on body in unhappy case

- functional-tests/tests/test_send_rtp.py
This PR proposes to add a test that makes assertion on the body of a 400 call. The description of the error should be clear.
- add test on send
Run:
> feat: [SRTP-258] Add test on descriptive error body

- .pre-commit-config.yaml
- functional-tests/tests/test_send_rtp.py
With this change we add an assertion on RTP location in response of a send request.
- add assertion on happy case
Run:
> feat: [SRTP-259] Add assertion on RTP location

- functional-tests/tests/test_activation.py
This PR proposes to change an assertion on activation test.
Run:
> feat: [SRTP-258] Modify assertion

- .github/workflows/run_tests.yml
This PR proposes to change report publishing condition.
- change GitHub action steps condition.
With this change we avoid incomplete test report publishing while running tests from branches.
Run:
> Fix incomplete report publishing

- api/callback.py
- api/send_rtp.py
- config.yaml
- config/.secrets_template.yaml
- functional-tests/tests/test_callback.py
- functional-tests/tests/test_debtor_service_provider.py
- functional-tests/tests/test_mock.py
- functional-tests/tests/test_send_rtp.py
This PR proposes to add callback test.
- add happy case test
With this change we test our callback endpoint. The test is currently failing, waiting for QWAC certificate.
Run:
> feat: [SRTP-322] Add callback tests

- .github/workflows/extract_allure_fail_rate.yml
- .github/workflows/run_tests.yml
add double quote to send_notification to match with set value.
notifications were not being sent on slack.
> fix: slack notifications job

- api/get_rtp.py
- config.yaml
- functional-tests/pytest.ini
- functional-tests/tests/test_get_rtp.py
add new functional test for new get rtp API.
new API to be tested
> feat [SRTP-530]: add get rtp tests

- functional-tests/tests/test_activation.py
Change status code check that returns on an already activated debtor.
status code has been changed, also need to be changed in test suite.
> chore: [SRTP-480] change on-error status code

- .github/workflows/run_tests.yml
- config/.secrets_template.yaml
- config/configuration.py
- functional-tests/tests/test_send_rtp.py
- utils/dataset.py
Made changes in dataset to be able to insert custom payee_id.
payee_id not always can be random to be tested.
> fix: [SRTP-569] cbi payee_id

- functional-tests/pytest.ini
- functional-tests/tests/test_callback.py
- utils/dataset.py
Creation of a rtp send before callback.
callback payload using a real originalMsgId.
Callback payload has been changed and test was failing.
> fix: [SRTP-584] callback payload

- utils/dataset.py
> fix: re import

- functional-tests/pytest.ini
- functional-tests/tests/test_debtor_service_provider_availability.py
- functional-tests/tests/test_send_rtp.py
- utils/dataset.py
Add unhappy path for send to POSTE.
changes improve the reliability of the availability test case to POSTE.
> feat: [SRTP-627] add unhappy path send poste availability

- config.yaml
change cbi endpoint to reflect the new provided from cbi.
new endpoint needed provided from cbi.
> feat: [SRTP-625] change cbi endpoint to a new one

- .gitignore
- performance-tests/tests/rtp-activator/activation-finder.js
- performance-tests/tests/rtp-activator/deactivation-finder.js
- performance-tests/utils/batch-utils.js
- performance-tests/utils/metrics-utils.js
- performance-tests/utils/reporting-utils.js
- performance-tests/utils/summary-utils.js
- performance-tests/utils/teardown-utils.js
- performance-tests/utils/utils.js
This PR improves the performance testing framework by adding a deactivation stress test that is comparable to the existing activation test. The work includes refactoring common utilities to centralize test logic, report generation, and test completion handling. Key improvements include better dashboard persistence after test completion and a more modular architecture for test implementation.
- Added new `deactivation-finder.js` test script to test RTP deactivation under load
- Refactored common utilities into separate files for better code organization:
- `summary-utils.js`: Centralized report generation logic 
- `teardown-utils.js`: Generalized teardown functions for different test types
- `reporting-utils.js`: Made reporting more flexible to work with different test types
- Improved …
> feat: [SRTP-725] stress test deactivation

- performance-tests/README.md
- performance-tests/config/config.js
- performance-tests/tests/rtp-activator/activation-finder.js
- performance-tests/tests/rtp-activator/activation-flow.js
- performance-tests/tests/rtp-activator/deactivation-finder.js
- performance-tests/tests/service-registry/service-registry.js
- performance-tests/utils/utils.js
This PR implements stress test for _Service Registry_ endpoint: it follows the same pattern used by other existing stress tests that leverage `k6` package.
It also generalizes the `setupAuth` function by passing a given `ActorCredentials` instance, needed to select the right _client credentials_ for the given flow.
- Added `performance-tests/tests/service-registry/service-registry.js`;
- Added `ActorCredentials` enum in `performance-tests/utils/utils.js`;
- Generalized `setupAuth` function in `performance-tests/utils/utils.js`;
- Added configs for _Service Registry_ flow;
- Updated `README.md`.
This is needed to test the _Service Registry_ API.
> feat: [SRTP-722] add stress test for service registry

- functional-tests/tests/test_callback.py
fix name reference from `generate_callback_data_DS_08P_compliant` to `generate_callback_data_DS_08N_compliant` based on previous merged changes.
> fix: [SRTP-789] typo in callback reference

- gpd-massive/README.md
- gpd-massive/activation.py
- gpd-massive/auth.py
- gpd-massive/cleanup.py
- gpd-massive/config.py
- gpd-massive/generate_zip.py
- gpd-massive/upload-file.py
- gpd-massive/utilities.py
Added Python utility scripts to manage RTP activations and GPD massive uploads.
Scripts include activation creation, ZIP generation, upload to GPD API, activation cleanup (remote deactivation + local artifact deletion).
- activation.py → create a new activation and save FISCAL_CODE to .env
- generate_zip.py → generate massive debt position JSON + ZIP
- upload-file.py → trigger activation, generate ZIP, and upload to GPD massive endpoint
- cleanup.py → get activation ID, deactivate remotely, delete local artifacts
- Centralized base URLs in config.py
- Added .env handling via require_env and load_dotenv in utilities.py
Provides a complete workflow for creating, uploading, and cleaning up test data in RTP UAT, ensuring a reproducible and automated test process without manual intervention. …
> feat: [SRTP-728] Stress-test create RTP
